In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

In [9]:
df = pd.read_csv('homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [7]:
mid_value = df.bedrooms.median()
mid_value

4.0

In [17]:
df.bedrooms = df.bedrooms.fillna(mid_value)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [12]:
regressor = linear_model.LinearRegression()
regressor.fit(df[['area','bedrooms','age']], df.price)

LinearRegression()

In [13]:
regressor.predict([[3000,4,40]])

array([521797.13165825])

In [14]:
regressor.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [15]:
regressor.intercept_

221323.00186540408

# Excercise

In [8]:
ef = pd.read_csv('hiring.csv')
ef

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [9]:
mean_value = ef['test_score(out of 10)'].mean()
ef['test_score(out of 10)'] = ef['test_score(out of 10)'].fillna(mean_value)

In [10]:
ef

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN               8.000000                           9      50000
1        NaN               8.000000                           6      45000
2       five               6.000000                           7      60000
3        two              10.000000                          10      65000
4      seven               9.000000                           6      70000
5      three               7.000000                          10      62000
6        ten               7.857143                           7      72000
7     eleven               7.000000                           8      80000

In [11]:
ef.experience = ef.experience.fillna('zero')
ef

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero               8.000000                           9      50000
1       zero               8.000000                           6      45000
2       five               6.000000                           7      60000
3        two              10.000000                          10      65000
4      seven               9.000000                           6      70000
5      three               7.000000                          10      62000
6        ten               7.857143                           7      72000
7     eleven               7.000000                           8      80000

In [61]:
pip install word2number


  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5591 sha256=09bfe3252d2d798c247144121e8b889e749d270aa243ad4926f7a342963a2737
  Stored in directory: c:\users\pcw\appdata\local\pip\cache\wheels\cb\f3\5a\d88198fdeb46781ddd7e7f2653061af83e7adb2a076d8886d6
Successfully built word2number


In [12]:
from word2number import w2n

In [13]:
ef.experience = ef.experience.apply(w2n.word_to_num)
ef

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0               8.000000                           9      50000
1           0               8.000000                           6      45000
2           5               6.000000                           7      60000
3           2              10.000000                          10      65000
4           7               9.000000                           6      70000
5           3               7.000000                          10      62000
6          10               7.857143                           7      72000
7          11               7.000000                           8      80000

In [14]:
import math
ef['test_score(out of 10)'] = ef['test_score(out of 10)'].apply(math.floor)
ef

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                      8                           9      50000
1           0                      8                           6      45000
2           5                      6                           7      60000
3           2                     10                          10      65000
4           7                      9                           6      70000
5           3                      7                          10      62000
6          10                      7                           7      72000
7          11                      7                           8      80000

In [15]:
reg = linear_model.LinearRegression()
reg.fit(ef.drop(['salary($)'],axis = 1), ef['salary($)'])

LinearRegression()

In [16]:
reg.predict([[2,9,6]])

array([53713.86677124])

In [3]:
pip install pickle-mixin

  Created wheel for pickle-mixin: filename=pickle_mixin-1.0.2-py3-none-any.whl size=6003 sha256=645ae9297cf49e1f4a72e1db73dca165339b7b409d71332852553d8695b25a72
  Stored in directory: c:\users\pcw\appdata\local\pip\cache\wheels\2a\a4\6c\83bfbc3b94f1bb43d634b07a6a893fd437a45c58b29aea5142
Successfully built pickle-mixin
Note: you may need to restart the kernel to use updated packages.


In [5]:
import pickle

In [23]:
with open('model_pickle','wb') as f:
    pickle.dump(reg,f)

In [24]:
with open('model_pickle','rb') as f:
    mo = pickle.load(f)

In [25]:
mo.predict([[2,9,6]])

array([53713.86677124])

## Method 2 to save model


In [27]:
import joblib

In [31]:
joblib.dump(reg, ' model_joblib.pckl')

[' model_joblib.pckl']

In [32]:
mo_2 = joblib.load('model_joblib.pckl')

FileNotFoundError: [Errno 2] No such file or directory: 'model_joblib.pckl'