In [70]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.datasets import load_digits

In [3]:
digits = load_digits()

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size = 0.2)

In [17]:
def model_score(model, X_train, X_test , y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [53]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [19]:
model_score(DecisionTreeClassifier(), X_train, X_test, y_train, y_test)

0.8555555555555555

In [20]:
model_score(RandomForestClassifier(), X_train, X_test, y_train, y_test)

0.9861111111111112

In [21]:
model_score(LogisticRegression(), X_train, X_test, y_train, y_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.975

## using KFold validation

In [22]:
from sklearn.model_selection import KFold


In [32]:
kf = KFold(n_splits = 3)

In [33]:
for train_index, test_index in kf.split(range(1,10)):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


## Stratified KFold

In [37]:
tree_scores = []
log_scores = []
forest_scores = []
                                                    # We actually have a sklearn function to do the same work as this function
                                                        # cross_val_scores()
from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits = 10)

for train_index, test_index in skf.split(digits.data, digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    log_scores.append(model_score(LogisticRegression(),X_train, X_test, y_train, y_test))
    tree_scores.append(model_score(DecisionTreeClassifier(),X_train, X_test, y_train, y_test))  
    forest_scores.append(model_score(RandomForestClassifier(),X_train, X_test, y_train, y_test))    

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

In [39]:
tree_scores


[0.7888888888888889,
 0.8833333333333333,
 0.8166666666666667,
 0.8,
 0.7888888888888889,
 0.8888888888888888,
 0.8666666666666667,
 0.7988826815642458,
 0.8212290502793296,
 0.7932960893854749]

In [40]:

log_scores


[0.9055555555555556,
 0.9611111111111111,
 0.8777777777777778,
 0.9277777777777778,
 0.9444444444444444,
 0.9666666666666667,
 0.95,
 0.9385474860335196,
 0.8715083798882681,
 0.9385474860335196]

In [41]:
forest_scores

[0.9,
 0.9833333333333333,
 0.9444444444444444,
 0.9333333333333333,
 0.9666666666666667,
 0.9611111111111111,
 0.9666666666666667,
 0.9608938547486033,
 0.9329608938547486,
 0.9497206703910615]

## cross_val_score()

In [45]:
from sklearn.model_selection import cross_val_score


In [66]:
log_scores = cross_val_score(LogisticRegression(), digits.data, digits.target, cv = 10)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

In [68]:
log_scores

array([0.90555556, 0.96111111, 0.87777778, 0.92777778, 0.94444444,
       0.96666667, 0.95      , 0.93854749, 0.87150838, 0.93854749])

In [59]:
tree_scores = cross_val_score(DecisionTreeClassifier(criterion = 'gini'), digits.data, digits.target, cv = 10)

In [60]:
tree_scores

array([0.77777778, 0.84444444, 0.82777778, 0.8       , 0.77222222,
       0.89444444, 0.87222222, 0.81564246, 0.81564246, 0.81564246])

In [51]:
forest_scores = cross_val_score(RandomForestClassifier(), digits.data, digits.target, cv = 10)

In [52]:
forest_scores

array([0.93333333, 0.95555556, 0.94444444, 0.92777778, 0.95555556,
       0.96666667, 0.99444444, 0.96089385, 0.93296089, 0.9273743 ])

In [54]:
svm_scores = cross_val_score(SVC(), digits.data, digits.target, cv = 10)

In [55]:
svm_scores

array([0.94444444, 0.98888889, 0.92777778, 0.96666667, 0.98333333,
       0.98888889, 0.98888889, 0.99441341, 0.96089385, 0.95530726])

In [71]:
np.average(log_scores)

0.928193668528864

In [72]:
np.average(tree_scores)

0.8235816263190564

In [74]:
np.average(forest_scores)

0.9499006828057107

In [75]:
np.average(svm_scores)   # best model till here , now tune your model for more accuracy

0.9699503414028554